# Generated by Django 5.2.6 on 2025-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='completion_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='duration_hours',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(default='Certificate of Completion', max_length=255),
        ),
    ]
