name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: project_lms_user
          POSTGRES_DB: project_lms_db
          POSTGRES_PASSWORD: supersecretpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U project_lms_user -d project_lms_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations and checks
        env:
          DATABASE_NAME: project_lms_db
          DATABASE_USER: project_lms_user
          DATABASE_PASSWORD: supersecretpassword
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
        run: |
          python project_lms/manage.py migrate --noinput
          python project_lms/manage.py check

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend deps
        working-directory: project_lms/lms-frontend
        run: |
          npm ci
      - name: Build frontend
        working-directory: project_lms/lms-frontend
        run: |
          npm run build
